program NAME;

uses Complex;

var
    a, b, c, d : ComplexType;

begin
	a := ComplexNum(3, 4);
    b := ComplexNum(0, 1);
    c := a * b;
    d := 1.5;
    writeln(AnsiString(a));
    writeln(Abs(a):2:3);
    writeln(Arg(a):2:3);
    writeln(AnsiString(b));
    writeln(Abs(b):2:3);
    writeln(Arg(b):2:3);
    writeln(AnsiString(c));
    writeln(Abs(c):2:3);
    writeln(Arg(c):2:3);
    writeln(AnsiString(d));
    writeln(AnsiString(c+d));
    writeln();
    writeln('pow,log,root,etc');
    writeln(AnsiString(Exp(1)));
    writeln(AnsiString(Ln(Exp(2))));
    writeln(AnsiString(Log(3,81)));
    writeln(AnsiString(Log(-3,81)));
    writeln(AnsiString(Pow(4,5)));
    writeln(AnsiString(Root(64,2)));
    writeln(AnsiString(Root(64,3)));
    writeln(AnsiString(Root(64,4)));
    writeln(AnsiString(Root(81,4)));
    writeln(AnsiString(Root(-64,2)));
    writeln(AnsiString(Root(-64,3)));
    writeln(AnsiString(Root(-64,4)));
    writeln(AnsiString(Root(-81,4)));
    writeln(AnsiString(Root(64,-2)));
    writeln(AnsiString(Root(64,-3)));
    writeln(AnsiString(Root(64,-4)));
    writeln(AnsiString(Root(81,-4)));
    writeln(AnsiString(Root(-64,-2)));
    writeln(AnsiString(Root(-64,-3)));
    writeln(AnsiString(Root(-64,-4)));
    writeln(AnsiString(Root(-81,-4)));
    writeln(AnsiString(Pow(Root(-81,4),4)));
    writeln(AnsiString(Pow(Root(-64,3),3)));
    writeln(AnsiString(Cub(Root(-64,3))));
    writeln(AnsiString(Pow(Root(64,2),2)));
    writeln(AnsiString(Pow(Root(-64,2),2)));
    writeln();
    writeln('trig');
    writeln(AnsiString(Sin(3.14)));
    writeln(AnsiString(Sin(Pi)));
    writeln(AnsiString(Cos(Pi)));
    writeln(AnsiString(Imag*Sin(Pi)));
    writeln(AnsiString(Cos(Pi) + Imag*Sin(Pi)));
    writeln(AnsiString(Cos(Pi)));
    writeln(AnsiString(Imag(Sin(Pi))));
    writeln(AnsiString(Cos(Pi) + Imag(Sin(Pi))));
    writeln(AnsiString(3+4*Imag));
    writeln(AnsiString(3+Imag(4)));
    writeln();
    writeln(AnsiString(Sin(0)));
    writeln(AnsiString(Sin(0.5*Pi)));
    writeln(AnsiString(Sin(Pi)));
    writeln(AnsiString(Sin(1.5*Pi)));
    writeln(AnsiString(Sin(2*Pi)));
    writeln();
    writeln(AnsiString(Cos(0)));
    writeln(AnsiString(Cos(0.5*Pi)));
    writeln(AnsiString(Cos(Pi)));
    writeln(AnsiString(Cos(1.5*Pi)));
    writeln(AnsiString(Cos(2*Pi)));
    writeln();
    writeln(AnsiString(Imag));
    writeln(AnsiString(Imag(Imag)));
    writeln(AnsiString(Imag*Imag));
    writeln(AnsiString(Pow(Imag, 2)));
    writeln();
    writeln(AnsiString(Arccos(Imag)));
    writeln(AnsiString(Arctan(1)*4));
    writeln(AnsiString(Arcsin(2)));
    writeln(AnsiString(Arcsec(1)));
    writeln(AnsiString(Arcsec(2)));
    writeln(AnsiString(Arcsec(3)));
    writeln(AnsiString(Arcsec(Imag)));
    writeln();
    writeln(AnsiString(MinusOneTo(1)));
    writeln(AnsiString(MinusOneTo(5/4)));
    writeln(AnsiString(MinusOneTo(3/2)));
    writeln(AnsiString(MinusOneTo(7/4)));
    writeln(AnsiString(MinusOneTo(2)));
    writeln(AnsiString(MinusOneTo(9/4)));
    writeln(AnsiString(MinusOneTo(5/2)));
    writeln(AnsiString(MinusOneTo(11/4)));
    writeln(AnsiString(MinusOneTo(3)));
end.
