program NAME;

uses Complex;

begin
    writeln(AnsiString(ComplexNumPolar(1, Pi/4)));
    writeln();
    writeln('newton');
    writeln(AnsiString(Newton(0,0)));
    writeln(AnsiString(Newton(1,0)));
    writeln(AnsiString(Newton(1,1)));
    writeln(AnsiString(Newton(2,0)));
    writeln(AnsiString(Newton(2,1)));
    writeln(AnsiString(Newton(2,2)));
    writeln(AnsiString(Newton(3,0)));
    writeln(AnsiString(Newton(3,1)));
    writeln(AnsiString(Newton(3,2)));
    writeln(AnsiString(Newton(3,3)));
    writeln(AnsiString(Newton(10,2)));
    writeln(AnsiString(Newton(10.5,2)));
    writeln(AnsiString(Newton(2+Imag(3),2)));
    writeln();
    writeln('bernoulli');
    writeln(AnsiString(bernoulli_num(0)));
    writeln(AnsiString(bernoulli_num(1)));
    writeln(AnsiString(bernoulli_num(2)));
    writeln(AnsiString(bernoulli_num(3)));
    writeln(AnsiString(bernoulli_num(4)));
    writeln(AnsiString(bernoulli_num(5)));
    writeln(AnsiString(bernoulli_num(6)));
    writeln(AnsiString(bernoulli_num(7)));
    writeln(AnsiString(bernoulli_num(8)));
    writeln(AnsiString(bernoulli_num(9)));
    writeln(AnsiString(bernoulli_num(10)));
    writeln(AnsiString(bernoulli_num(11)));
    writeln(AnsiString(bernoulli_num(12)));
    writeln(AnsiString(bernoulli_num(13)));
    writeln(AnsiString(bernoulli_num(14)));
    writeln(AnsiString(bernoulli_num(15)));
    writeln(AnsiString(bernoulli_num(16)));
    writeln(AnsiString(bernoulli_num(32)));
    writeln(AnsiString(bernoulli_num(48)));
    writeln(AnsiString(bernoulli_num(49)));
    writeln(AnsiString(bernoulli_num(50)));
    writeln(AnsiString(bernoulli_num(99)));
    writeln(AnsiString(bernoulli_num(100)));
    writeln();
    writeln('ei,li');
    writeln(AnsiString(Sinc(-1)));
    writeln(AnsiString(Sinc(0)));
    writeln(AnsiString(Sinc(1)));
    writeln(AnsiString(Sinc(Pi)));
    writeln(AnsiString(Sinc(2*Pi)));
    writeln(AnsiString(Sinc(3+Imag(4))));
    writeln();
    writeln(AnsiString(ExpIntC1(-2.5)));
    writeln(AnsiString(ExpIntC1(-2))); 
    writeln(AnsiString(ExpIntC1(-1)));  
    writeln(AnsiString(ExpIntC1(0)));
    writeln(AnsiString(ExpIntC1(1)));
    writeln(AnsiString(ExpIntC1(Pi)));
    writeln(AnsiString(ExpIntC1(2*Pi)));
    writeln(AnsiString(ExpIntC1(200*Pi)));
    writeln(AnsiString(ExpIntC1(3+Imag(4))));
    //writeln(AnsiString(ExpIntC(-1, 2)));
    writeln(AnsiString(ExpIntC(0, 1)));
    writeln(AnsiString(ExpIntC(1, 1)));
    writeln(AnsiString(ExpIntC(Pi, 1)));
    writeln(AnsiString(ExpIntC(2*Pi, 1)));
    writeln(AnsiString(ExpIntC(200*Pi, 1)));
    writeln(AnsiString(ExpIntC(3+Imag(4),1)));
    writeln(AnsiString(ExpIntC(0, 2)));
    writeln(AnsiString(ExpIntC(1, 2)));
    writeln(AnsiString(ExpIntC(Pi, 2)));
    writeln(AnsiString(ExpIntC(2*Pi, 2)));
    writeln(AnsiString(ExpIntC(200*Pi, 2)));
    writeln(AnsiString(ExpIntC(3+Imag(4),2)));
    writeln(AnsiString(ExpIntC(0, 3)));
    writeln(AnsiString(ExpIntC(1, 3)));
    writeln(AnsiString(ExpIntC(Pi, 3)));
    writeln(AnsiString(ExpIntC(2*Pi, 3)));
    writeln(AnsiString(ExpIntC(200*Pi, 3)));
    writeln(AnsiString(ExpIntC(3+Imag(4),3)));
    writeln();
    writeln('ln '+AnsiString(Ln(-1)));
    writeln(AnsiString(ExpInt(-2)));
    writeln(AnsiString(ExpInt(-1)));
    writeln(AnsiString(ExpInt(Ln(-1))));
    writeln(AnsiString(ExpInt(3+Imag(4))));
    writeln(AnsiString(ExpInt(0)));
    writeln(AnsiString(ExpInt(1)));
    writeln(AnsiString(ExpInt(2)));
    writeln(AnsiString(ExpInt(Pi)));
    writeln(AnsiString(ExpInt(2*Pi)));
    writeln(AnsiString(ExpInt(200*Pi)));
    writeln();
    writeln(AnsiString(LogInt(-2)));
    writeln(AnsiString(LogInt(-1)));
    writeln(AnsiString(LogInt(0)));
    writeln(AnsiString(LogInt(1)));
    writeln(AnsiString(LogInt(2)));
    writeln(AnsiString(LogInt(Pi)));
    writeln(AnsiString(LogInt(2*Pi)));
    writeln(AnsiString(LogInt(200*Pi)));
    writeln();
    writeln(AnsiString(LogInt2(-2)));
    writeln(AnsiString(LogInt2(-1)));
    writeln(AnsiString(LogInt2(0)));
    writeln(AnsiString(LogInt2(1)));
    writeln(AnsiString(LogInt2(2)));
    writeln(AnsiString(LogInt2(Pi)));
    writeln(AnsiString(LogInt2(2*Pi)));
    writeln(AnsiString(LogInt2(200*Pi)));
    writeln();
    writeln('sin,cos');
    writeln(AnsiString(SinInt(-1)));
    writeln(AnsiString(SinInt(-0.1)));
    writeln(AnsiString(SinInt(0)));
    writeln(AnsiString(SinInt(0.1)));
    writeln(AnsiString(SinInt(1)));
    writeln(AnsiString(SinInt(Pi)));
    writeln(AnsiString(SinInt(2*Pi)));
    writeln(AnsiString(SinInt(200*Pi)));
    writeln(AnsiString(SinInt(3+Imag(4))));
    writeln(AnsiString(CosInt(-1)));
    //writeln(AnsiString(CosInt(0)));
    writeln(AnsiString(CosInt(1)));
    writeln(AnsiString(CosInt(Pi)));
    writeln(AnsiString(CosInt(2*Pi)));
    writeln(AnsiString(CosInt(200*Pi)));
    writeln(AnsiString(CosInt(3+Imag(4))));
    writeln(AnsiString(SinInt2(-1)));
    writeln(AnsiString(SinInt2(-0.1)));
    writeln(AnsiString(SinInt2(0)));
    writeln(AnsiString(SinInt2(0.1)));
    writeln(AnsiString(SinInt2(1)));
    writeln(AnsiString(SinInt2(Pi)));
    writeln(AnsiString(SinInt2(2*Pi)));
    writeln(AnsiString(SinInt2(200*Pi)));
    writeln(AnsiString(CosInt2(-1)));
    //writeln(AnsiString(CosInt2(0)));
    writeln(AnsiString(CosInt2(1)));
    writeln(AnsiString(CosInt2(Pi)));
    writeln(AnsiString(CosInt2(2*Pi)));
    writeln(AnsiString(CosInt2(200*Pi)));
end.
